import { expect, test } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

/* The one thing the Compose smoke cannot check: that the whole
   upload → review → correct → approve → CSV flow is actually completable in the
   interface, by a person, with a keyboard and a mouse.

   It uploads a *generated* fictional invoice rather than a committed fixture,
   for two reasons. Uploads are deduplicated by SHA-256, so a committed fixture
   would return 409 on a second run against the same demo. And an unseen
   document exercises the offline heuristic reader (ADR-015) — the path a real
   visitor takes — instead of the fixture registry. */

const invoiceNumber = (): string => `E2E-${randomUUID().slice(0, 8).toUpperCase()}`;

/* A minimal, valid, single-page text PDF. It is written by hand rather than
   generated by a tool so the test needs no Python, no Poppler, and no fixture
   on disk; the byte offsets in the xref table are computed below. */
function buildInvoicePDF(number: string): Buffer {
  const lines = [
    'Northwind Trading Ltd.',
    'billing@northwind.example',
    `Invoice Number: ${number}`,
    'Issue Date: 2026-06-11',
    'Due Date: 2026-07-11',
    'Currency: USD',
    'Subtotal: 71.00',
    'VAT (19%): 13.49',
    'Total: 84.49',
  ];
  const text = lines
    .map((line, index) => `BT /F1 12 Tf 60 ${740 - index * 22} Td (${line}) Tj ET`)
    .join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${text.length} >>\nstream\n${text}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((body, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;
  return Buffer.from(pdf, 'latin1');
}

test('a person can upload, correct, approve, and export an invoice', async ({ page }) => {
  const number = invoiceNumber();
  const directory = await mkdtemp(join(tmpdir(), 'invoiceflow-e2e-'));
  const file = join(directory, 'invoice.pdf');
  await writeFile(file, buildInvoicePDF(number));

  await page.goto('/app');
  await expect(page.getByRole('heading', { name: /prepare an invoice for review/i })).toBeVisible();

  // Upload through the real file input, not an API call.
  await page.getByLabel('Invoice file').setInputFiles(file);

  // The shell navigates into the review as soon as the server accepts the file.
  await expect(page).toHaveURL(/\/app\/documents\/[0-9a-f-]{36}$/, { timeout: 30_000 });

  // The worker is durable and asynchronous, so the review is not ready
  // immediately. The form appearing is the signal that extraction finished.
  const form = page.getByRole('form', { name: 'Editable invoice proposal' });
  await expect(form).toBeVisible({ timeout: 90_000 });
  await expect(page.getByText('Needs review')).toBeVisible();

  // The original must be on screen beside the data — that is the product.
  await expect(page.getByRole('region', { name: 'Invoice review workspace' })).toBeVisible();

  // Correct one field. Saving creates a new immutable version, never an update.
  const supplier = form.getByLabel('Supplier name');
  await supplier.fill('Northwind Trading Limited');
  await expect(page.getByText(/unsaved changes/i)).toBeVisible();

  await page.getByRole('button', { name: 'Save correction' }).click();
  await expect(page.getByText(/unsaved changes/i)).toBeHidden();
  await expect(page.getByText('Human-reviewed proposal')).toBeVisible();
  await expect(form.getByLabel('Supplier name')).toHaveValue('Northwind Trading Limited');

  // Approval targets the exact version shown and must be confirmed explicitly.
  await page.getByRole('button', { name: /^Approve version \d+$/ }).click();
  const approveDialog = page.getByRole('dialog');
  await expect(approveDialog).toBeVisible();
  await expect(approveDialog).toContainText(/cannot be undone/i);
  await approveDialog.getByRole('button', { name: 'Confirm approval' }).click();

  await expect(page.getByText('Approved', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Save correction' })).toHaveCount(0);

  // Only an approved version can be exported.
  await page.getByRole('button', { name: 'Download CSV Export' }).click();
  const csvDialog = page.getByRole('dialog');
  await expect(csvDialog).toBeVisible();

  const [download] = await Promise.all([
    page.waitForEvent('download'),
    csvDialog.getByRole('button', { name: 'Confirm CSV export' }).click(),
  ]);
  expect(download.suggestedFilename()).toMatch(/^invoice-[0-9a-f-]{36}-v\d+\.csv$/);
  await expect(page.getByText(/CSV v1 downloaded for approved version/i)).toBeVisible();

  // The export moved the document to its terminal state, and the audit history
  // records the whole path rather than only the final value.
  await expect(page.getByText('Exported', { exact: true })).toBeVisible();
  // Audit actions are rendered with underscores replaced by spaces.
  await expect(page.getByText(/document approved/i)).toBeVisible();
  await expect(page.getByText(/human review saved/i)).toBeVisible();
});

test('the document list shows an uploaded document and opens it', async ({ page }) => {
  const directory = await mkdtemp(join(tmpdir(), 'invoiceflow-e2e-'));
  const file = join(directory, 'invoice.pdf');
  await writeFile(file, buildInvoicePDF(invoiceNumber()));

  await page.goto('/app');
  await page.getByLabel('Invoice file').setInputFiles(file);
  await expect(page).toHaveURL(/\/app\/documents\/[0-9a-f-]{36}$/, { timeout: 30_000 });
  const documentID = new URL(page.url()).pathname.split('/').pop();

  // A document must be reachable without the URL the upload returned, which is
  // the whole point of the list. The row is located by the document's own link
  // rather than by an extracted value, so the assertion tests the list, not the
  // heuristic reader's accuracy.
  await page.goto('/app');
  const link = page.locator(`a[href="/app/documents/${documentID}"]`);
  await expect(link).toBeVisible({ timeout: 90_000 });
  await link.click();
  await expect(page).toHaveURL(new RegExp(`/app/documents/${documentID}$`));
  await expect(page.getByRole('form', { name: 'Editable invoice proposal' })).toBeVisible({
    timeout: 90_000,
  });
});
